### ISSUE TITLE
lack of config.cs file

### ISSUE THREAD

**Issue by belle2392** [InGaN/CookbookWin10#1]
missing the config file to test the solution.
Tanks Giovanni

**Comment by PA4KEV** [comment]
It is left out on purpose because it contains data not meant to be public.
I kind of abandoned this school project, if I have some time to kill I will upload the server files and config file.

you can create your own `config.cs` in the root of the project. Replace the values with the settings of your own server.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CookbookWin10
{
    public static class Config
    {
        public static string URL_MAIN = "http://www.myhost.com/";

        public static string URL_GALLERY = URL_MAIN + "/gallery/";
        private static string URL_JSON_CALL = URL_MAIN + "json_call.php";

        public static string URL_JSON_MAIN = URL_JSON_CALL + "?section=main";
        public static string URL_JSON_ID = URL_JSON_CALL + "?id=";
    }
}
```
